baseurl             = "https://prakashpaudel.com/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-us"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "cocoa"
author              = "Prakash Paudel"
title               = "Prakash Paudel"
pygmentsuseclasses  = true
pluralizelisttitles = false
googleAnalytics     = ""

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "Bookshelf"
weight                 = -110
identifier             = "bookshelf"
url                    = "/bookshelf/"

[[menu.main]]
name                   = "About"
weight                 = -100
identifier             = "about"
url                    = "/about/"

[params]
include_rss            = false                          # include RSS <link> tag in <head> and show RSS icon
latestpostscount       = 5                             # how many posts to display on the home page
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "Prakash Paudel"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Personal Website of Prakash Paudel"
email                  = "total.prakash@gmail.com"
extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
faviconfile            = "img/leaf.ico"
# github                 = "//github.com/prakashpaudel"
# twitter                = "//twitter.com/pkpd0"
lang                   = "en-us"
noshowreadtime         = true                         # if true, don't show "<x> minutes read" in posts
selfintro              = ""                            # appears in the site header when set to a non-empty string

highlightjs            = true
# highlightjslanguages = ["go"]                        # additional languages not included in the "common" set
# highlightjsStyle     = "darcula"

# avatar                 = "img/profile.png" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
gravatar             = "cba6e80d51710c045315d3ad26b69c06"                # gravatar hash. see https://en.gravatar.com/site/implement/hash/. do not use in the same time as avatar
